### PR TITLE
Middlewares

### LINKED ISSUE #24: Handle errors
Add middlewares to handle errors and prevent app from crashing completely.

### PR DESCRIPTION
**Pull request by ZuluNovember**
Closes #24 

# Middlewares

Added 2 middlewares for:
- Checking authentication
- Handling errors

**Use `checkAuthentication` middleware on the auth guarded end points**

### CODE REVIEW

**Review by Kishimoto96 — APPROVED** [review]
super clear thanks

**Review by ibraheemhajjar — APPROVED** [review]
looks fine, nice work eniz @ZuluNovember

File: src/middlewares/errorHandler.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+const handleErrors = (err, req, res, next) => {
+  //  Add logger when it's merged
+  res.status(500).json({ message: 'Server ran into an error', err });
+};
+
+module.exports = handleErrors;
```
Comment (Shrreya) [inline src/middlewares/errorHandler.js:6]: Will this middleware use any params or run any conditions to check there's an error?

File: src/middlewares/errorHandler.js [hunk 2]
```diff
@@ -0,0 +1,6 @@
+const handleErrors = (err, req, res, next) => {
+  //  Add logger when it's merged
```
Comment (Shrreya) [inline src/middlewares/errorHandler.js:2]: I think logger has been merged to main.

**Review by Shrreya — CHANGES_REQUESTED** [review]
I think a main merge is required, and I have 1 question below.

File: src/middlewares/errorHandler.js (hunk 1 above)
Comment (ZuluNovember) [reply src/middlewares/errorHandler.js:6]: My intention was build an error handler that we can use instead of express' built-in error handler. The benefit we get from doing that is that we can log our error. After checking the docs again, I'm adding a new condition to check if the server started writing response. Please let me know if I miss something

Comment (Shrreya) [reply src/middlewares/errorHandler.js:12]: Okay now that you've added the condition to check if response headers were sent, it makes sense. Earlier I was wondering when will the error handler take effect.

Just 1 small suggestion you can rename this function to `errorHandler` which is the name you've used when importing the function in app.js file. Or you could use this approach without any naming:

```js
module.exports = (err, req, res, next) => {
.
.
.
.
```

**Review by Shrreya — APPROVED** [review]
@ZuluNovember I'm marking this approved, I just made 1 small suggestion in the previous comment thread. You can work on that and then merge this.
